---
title: "STEAMprice"

---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

## lib
```{r}
library(arm)
library(ggplot2)
library(tidyr)
library(car)
library(dplyr) 
library(broom) #install this lib first
library(leaps) 
library(sandwich)
library(MASS)
library(visdat)
library(corrplot)
```

## EDA 
```{r}
Steam<-read.csv("df_all_games.csv",header = TRUE)
head(Steam)

# Remove the first four columns
Steam<-Steam[,-c(1:4)]

#Also remove score_rank as NA >50%
Steam<-Steam[,-1]

#Also remove userscore as NA >50%
Steam<-Steam[,-3]

#check missing vales
sum(is.na(Steam))

#create a new coloum num_reviews that is postive+negative
Steam$num_reviews=Steam$positive+Steam$negative

#change postive&negative to percentage
Steam$positive=Steam$positive/Steam$num_reviews
Steam$negative=Steam$negative/Steam$num_reviews

#remove the num_reviews <=200
Steam2<-Steam[Steam$num_reviews >= 200,]

#merg owners
Steam2$owners=as.factor(Steam2$owners)
levels(Steam2$owners)[levels(Steam2$owners) %in% c("0 .. 20,000","20,000 .. 50,000","50,000 .. 100,000")] <- "Low"
levels(Steam2$owners)[levels(Steam2$owners) %in% c("100,000 .. 200,000","200,000 .. 500,000","500,000 .. 1,000,000")] <- "Normal"
levels(Steam2$owners)[levels(Steam2$owners) %in% c("5,000,000 .. 10,000,000","2,000,000 .. 5,000,000","1,000,000 .. 2,000,000")] <- "High"
levels(Steam2$owners)[levels(Steam2$owners) %in% c("200,000,000 .. 500,000,000","50,000,000 .. 100,000,000","20,000,000 .. 50,000,000","10,000,000 .. 20,000,000")] <- "Very High"
summary(Steam2)
str(Steam2)

```

## plot1
```{r}

#EDA price histogram
hist(Steam2$price,breaks=100,col='blue',xlab='Price',main=
       'Price histogram')

#corrplot EDA
Steam_games<- Steam2[,c(1,2,4,5,6,7,8,9,10,11,12)]
r <- cor(Steam_games)
r

corrplot.mixed(cor(Steam_games),
               upper = "square",
               lower = "number",
               addgrid.col = "black",
               tl.col = "grey")

#EDA boxplot for owners
EDA_boxplot<-ggplot(data=Steam2,aes(x=owners, y=price))+geom_boxplot()#+scale_y_continuous(limits=c(0,2000000))
EDA_boxplot
```

#plot2 for why use sqrt(price)
```{r}
#plot the Dependent Continuous variable-price
qqnorm(Steam2$price)
qqline(Steam2$price)

Steam1<-Steam2
Steam1$price[Steam1$price == 0] <- 1
qqnorm(log(Steam1$price))
qqline(log(Steam1$price))

qqnorm(sqrt(Steam2$price))
qqline(sqrt(Steam2$price))

```

## modeling
```{r}
#sqrt version model 
Games_lm=lm(sqrt(price)~.,data = Steam2) #Full
Games_lm0=lm(sqrt(price)~1,data = Steam2) #Null 
GamesSqrt_st<- step(Games_lm0, scope=list(lower=Games_lm0, upper=Games_lm),direction="both")
summary(GamesSqrt_st)
Anova(GamesSqrt_st)

#remove num_reviews
Games_lm1=lm(sqrt(price)~initialprice 
             +discount
             +owners
             +positive
             +ccu
             +median_2weeks 
             +average_2weeks,data = Steam2) 
summary(Games_lm1)
Anova(Games_lm1)
vif(Games_lm1)

#remove average_2weeks as vif >10
Games_lm2=lm(sqrt(price)~initialprice 
             +discount
             +owners
             +positive
             +ccu
             +median_2weeks ,data = Steam2) 
summary(Games_lm2)
Anova(Games_lm2)

#remove median_2weeks as p=0.12510
Games_lm3=lm(sqrt(price)~initialprice 
             +discount
             +owners
             +positive
             +ccu,data = Steam2) 
summary(Games_lm3)
Anova(Games_lm3)
vif(Games_lm3)
```

## reprove the factors selection
```{r}
#best subset
GamesSqrt_sub<- regsubsets(sqrt(price)~.,data = Steam2, nbest=1)
par(mfrow = c(1,2))
plot(GamesSqrt_sub,scale="adjr2")
plot(GamesSqrt_sub,scale="bic")
```

## keep outliers
```{r}
#check  outliers
plot(rstandard(Games_lm3))
options(max.print=22000)
max(rstandard(Games_lm3))
sort(rstandard(Games_lm3))

outlier<-sort(abs(rstandard(Games_lm3))>3)
list(outlier)
out<-which(outlier == TRUE)
glimpse(out)
Steam3 <- Steam2[-out,]
#There exists 93 points that has absolute >3
Games_lm4=lm(sqrt(price)~initialprice 
             +discount
             +owners
             +positive
             +ccu,data = Steam3) 
summary(Games_lm4)
vif(Games_lm4)
#romoved the Outliers doesn't help to improve R square, and it even decreases
#keep Games_lm3
```

## keep high leverage points
```{r}
#Check high leverage points
plot(hatvalues(Games_lm3))
#k chosen to be 3
#(p/n) * k = (11/12662) * 3 ≈ 0.00260622
hatvalues(Games_lm3) 
sort(hatvalues(Games_lm3))
max(hatvalues(Games_lm3)) 

high_leverage_threshold = (11/12662) * 3
ggplot(aes(seq_along(hatvalues(Games_lm3)), 
           hatvalues(Games_lm3)), data=Steam2) + geom_point() +
  geom_hline(yintercept = high_leverage_threshold, linetype='dashed' , 
             color='red')+ xlab("Observation number")+
  ylab("Hat Values")

High_lever<-sort(abs(hatvalues(Games_lm3))>0.00260622)
HL<-which(High_lever == TRUE)
glimpse(HL)
SteamH <- Steam2[-HL,]

Games_lm5=lm(sqrt(price)~initialprice 
             +discount
             +owners
             +positive
             +ccu,data = SteamH) 
summary(Games_lm5)
vif(Games_lm5)
#romoved the high-leverage point doesn't help to improve R square, and it even decreases
#keep Games_lm3
```

## final model after removing influential points
```{r}
#infuential points
thresh <- 4/nrow(Steam2) # Using the 4/n threshold
ggplot(Games_lm3, aes(seq_along(.cooksd), .cooksd)) + 
  geom_col()+ 
  geom_hline(yintercept = thresh , linetype='dashed' , color='red')+ 
  xlab("Observation number")+ 
  ylab("Cook's D")

cooksdis <- cooks.distance(Games_lm3) 
infuential <- as.numeric(names(cooksdis)[cooksdis > thresh]) 
SteamI <- Steam2[-infuential,] 

Games_lm6=lm(sqrt(price)~initialprice 
             +discount
             +owners
             +positive
             +ccu,data = SteamI) 
summary(Games_lm6)
vif(Games_lm6)

car::avPlots(Games_lm6)

plot(Games_lm6, which=c(1,2))
hist(rstandard(Games_lm6), freq = FALSE , 
     main="Histogram of standardised residuals", 
     cex.main=0.8, xlab="Standardised residuals")
```
